### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by afiskon** [cofyc/perl6-redis#1]
Your tests should not depend on any external daemon. Use mock objects instead.

t/01-connect.t ............ 1/2 connect failed: Connection refused
  in method initialize at src/gen/CORE.setting:7764
  in method new at src/gen/CORE.setting:7744
  in method connect at lib/Redis.pm:97
  in block  at t/01-connect.t:17

t/01-connect.t ............ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
t/02-connection.t ......... connect failed: Connection refused
  in method initialize at src/gen/CORE.setting:7764
  in method new at src/gen/CORE.setting:7744
  in method connect at lib/Redis.pm:97
  in block  at t/02-connection.t:9

t/02-connection.t ......... Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
t/02-hashes.t ............. connect failed: Connection refused
  in method initialize at src/gen/CORE.setting:7764
  in method new at src/gen/CORE.setting:7744
  in method connect at lib/Redis.pm:97t/01-connect.t ............ 1/2 connect failed: Connection refused
  in method initialize at src/gen/CORE.setting:7764
  in method new at src/gen/CORE.setting:7744
  in method connect at lib/Redis.pm:97
  in block  at t/01-connect.t:17

t/01-connect.t ............ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
t/02-connection.t ......... connect failed: Connection refused
  in method initialize at src/gen/CORE.setting:7764
  in method new at src/gen/CORE.setting:7744
  in method connect at lib/Redis.pm:97
  in block  at t/02-connection.t:9

t/02-connection.t ......... Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
t/02-hashes.t ............. connect failed: Connection refused
  in method initialize at src/gen/CORE.setting:7764
  in method new at src/gen/CORE.setting:7744
  in method connect at lib/Redis.pm:97
  in block  at t/02-hashes.t:9

  in block  at t/02-hashes.t:9
.........

**Comment by diegok** [comment]
@Cofyc you can use the same technique used by perl5 Redis module (and I've copied for Resque) that is to run a local redis on a random port:

https://github.com/diegok/resque-perl/blob/master/t/lib/Test/SpawnRedisServer.pm

... and skip tests when no redis binary is available
